apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-coffee-backend
  labels:
    app: virtual-coffee
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: virtual-coffee
      component: backend
  template:
    metadata:
      labels:
        app: virtual-coffee
        component: backend
    spec:
      containers:
      - name: api
        image: ${BACKEND_IMAGE}:${BACKEND_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: virtual-coffee-config
              key: aws_region
        - name: DYNAMODB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: virtual-coffee-config
              key: dynamodb_endpoint
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: virtual-coffee-secrets
              key: jwt_secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: virtual-coffee-secrets
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: virtual-coffee-secrets
              key: aws_secret_access_key
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: virtual-coffee-secrets
              key: oauth_client_id
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: virtual-coffee-secrets
              key: oauth_client_secret
        - name: OAUTH_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: virtual-coffee-config
              key: oauth_redirect_uri
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5