apiVersion: v1
kind: Service
metadata:
  name: virtual-coffee-backend
  labels:
    app: virtual-coffee
    component: backend
spec:
  selector:
    app: virtual-coffee
    component: backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP