---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python linting and formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      # Run the Ruff linter
      - id: ruff
        args: [--fix]
      # Run the Ruff formatter
      - id: ruff-format

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [
          'types-requests',
          'types-PyYAML',
          'pydantic',
        ]

  # Python security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  # Kubernetes manifests validation
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  # Kubernetes manifests validation
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.301
    hooks:
      - id: checkov
        args: [
          "--framework", "kubernetes",
          "--skip-check", "CKV_K8S_21,CKV_K8S_35",
        ]
        files: ^k8s/.*\.ya?ml$

  # Dockerfile validation
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        args: ['--ignore', 'DL3008', '--ignore', 'DL3013', '--ignore', 'DL3018']

  # Terraform validation (if used in the future)
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
        files: \.tf$
      - id: terraform_validate
        files: \.tf$

  # JavaScript/TypeScript linting (for frontend)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.42.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint
          - eslint-config-prettier
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - typescript