apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-coffee-frontend
  labels:
    app: virtual-coffee
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: virtual-coffee
      component: frontend
  template:
    metadata:
      labels:
        app: virtual-coffee
        component: frontend
    spec:
      containers:
      - name: web
        image: ${FRONTEND_IMAGE}:${FRONTEND_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: virtual-coffee-config
              key: api_url
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5