apiVersion: v1
kind: Service
metadata:
  name: virtual-coffee-frontend
  labels:
    app: virtual-coffee
    component: frontend
spec:
  selector:
    app: virtual-coffee
    component: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP